global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Nginx监控
  - job_name: 'nginx'
    static_configs:
      - targets: ['datarecover-web:80']
    metrics_path: '/nginx_status'
    scrape_interval: 10s

  # 容器监控
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s
