version: '3.8'

services:
    nginx:
      image: nginx:alpine
      ports:
        - "80:80"  # 统一监听宿主机 80 端口
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - 318
        - dt
      networks:
        - web-net

    318:
      build: ./318 
      networks:
        - web-net
      # 无 ports 映射，仅内部访问

    dt:
      build: ./dt  # 使用本地 Dockerfile 构建 site2
      networks:
        - web-net
      # 无 ports 映射

networks:
  web-net:
    driver: bridge