services:
    nginx:
      image: nginx:alpine
      ports:
        - "80:80"  # 统一监听宿主机 80 端口
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - site-318
        - site-dt
        - site-zhenzhufen
      networks:
        - web-net

    site-318:
      build: ./318 
      networks:
        - web-net
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/health"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s
      # 无 ports 映射，仅内部访问

    site-dt:
      build: ./dt  # 使用本地 Dockerfile 构建 site2
      networks:
        - web-net
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/health"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s
      # 无 ports 映射

    site-zhenzhufen:
      build: ./zhenzhufen  # 使用本地 Dockerfile 构建 zhenzhufen
      networks:
        - web-net
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/health"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s
      # 无 ports 映射

networks:
  web-net:
    driver: bridge