# Traefik 主配置文件
api:
  dashboard: true
  insecure: true

# 入口点配置
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

# 证书解析器
certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@yongli.wang
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

# 提供者配置
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-network

# 日志配置
log:
  level: INFO
  filePath: "/var/log/traefik.log"

accessLog:
  filePath: "/var/log/access.log"
  format: json

# 指标配置
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true

# 中间件配置
http:
  middlewares:
    # 安全头中间件
    security-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          Strict-Transport-Security: "max-age=31536000; includeSubDomains"
          X-Frame-Options: "SAMEORIGIN"
          X-Content-Type-Options: "nosniff"
          X-XSS-Protection: "1; mode=block"
    
    # 压缩中间件
    compress:
      compress: {}
    
    # 限流中间件
    rate-limit:
      rateLimit:
        burst: 100
        average: 50
    
    # 重定向到 HTTPS
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

# 全局配置
global:
  checkNewVersion: false
  sendAnonymousUsage: false
