services:
  # 新都桥旅行网站服务
  xinduqiao-travel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xinduqiao-travel-website
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"  # 为HTTPS预留端口
    environment:
      - TZ=Asia/Shanghai
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
    volumes:
      # 日志持久化
      - ./logs/nginx:/var/log/nginx
      # 自定义配置（可选，仅在文件存在时挂载）
      # - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - xinduqiao-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xinduqiao.rule=Host(`318.yongli.wang`)"
      - "traefik.http.routers.xinduqiao.entrypoints=web"
      - "traefik.http.services.xinduqiao.loadbalancer.server.port=80"
      - "com.docker.compose.project=xinduqiao-travel"
      - "com.docker.compose.service=website"

  # Nginx反向代理（可选，用于多服务部署）
  nginx-proxy:
    image: nginx:alpine
    container_name: xinduqiao-proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./config/proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/proxy:/var/log/nginx
    depends_on:
      - xinduqiao-travel
    networks:
      - xinduqiao-network
    profiles:
      - proxy  # 使用 profile 控制是否启动

  # 监控服务（可选）
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    container_name: xinduqiao-exporter
    restart: unless-stopped
    ports:
      - "9113:9113"
    command:
      - '-nginx.scrape-uri=http://xinduqiao-travel:80/nginx_status'
    depends_on:
      - xinduqiao-travel
    networks:
      - xinduqiao-network
    profiles:
      - monitoring  # 使用 profile 控制是否启动

networks:
  xinduqiao-network:
    driver: bridge
    name: xinduqiao-travel-network

volumes:
  # 数据持久化卷
  nginx-logs:
    driver: local
  website-data:
    driver: local
