# 开发环境 Docker Compose 配置
# 使用方法: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d

version: '3.8'

services:
  xinduqiao-travel:
    # 开发环境配置
    restart: "no"
    ports:
      - "3000:80"  # 使用不同端口避免冲突
    
    # 开发环境环境变量
    environment:
      - TZ=Asia/Shanghai
      - NGINX_WORKER_PROCESSES=1
      - LOG_LEVEL=debug
      - DEBUG_MODE=true
    
    # 开发环境卷挂载（支持热重载）
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./logs/nginx:/var/log/nginx
      - ./config/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./config/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
    
    # 开发环境标签
    labels:
      - "com.docker.compose.project=xinduqiao-travel-dev"
      - "environment=development"

  # 开发工具
  nginx-dev-tools:
    image: nginx:alpine
    container_name: xinduqiao-dev-tools
    restart: "no"
    ports:
      - "8080:80"
    volumes:
      - ./dev-tools:/usr/share/nginx/html:ro
    networks:
      - xinduqiao-network
    profiles:
      - dev-tools

networks:
  xinduqiao-network:
    driver: bridge
